import { combineReducers } from "redux";
import { connectRouter } from "connected-react-router";
import Settings from "./Settings";
import Auth from "./Auth";
import Notes from "./Notes";
import Contact from "./Contact";
import Common from "./Common";
//import ReactTable from "./ReactTable";
import {
  Cardonereducer,
  Cardtworeducer,
  Cardthreereducer,
  Cardfourreducer,
  Cardfivereducer,
  Cardsixreducer,
  Raisedreducer,
  Newinstallreducer,
  Changeordersreducer,
  Disconnectordersreducer,
} from "./Cardonereducer";
import {
  Winchartreducer,
  Losschartreducer,
  Unresolvedchartreducer,
  Raisedchartreducer,
  Newinstallchartreducer,
  Changechartreducer,
  Disconnectchartreducer,
  Disputechartreducer,
  Invoicechartreducer,
  Indispchartreducer,
  InstallOrdersByBWreducer,
  InstallOrdersByTermreducer,
  InstallOrdersByOverallreducer,
  ChangeOrdersByDatereducer,
  DisconnectOrdersreducer,
  TopCircuitsWithChangesreducer,
  DisputesByCategoryreducer,
  InvoiceDrilldownreducer,
  DisputesDrillDownreducer,
  InstallOrdersDrillDownreducer,
  ChangeOrdersdrilldownreducer,
  DisconnectOrdersDrillDownreducer,
  DisputableCircuitsTablereducer,
  Amendenturlreducer,
  DisconnectOrdersDrillDownByDateReducer,
  InstallOrdersDrillDownByDateReducer,
  ChangeOrdersDrillDownByDateReducer,
  InvoiceNumberreducer,
  OpenLoseDisputesTablereducer,
  InvoicesDrillDownForMonth,
} from "./Chartreducers";
import { SupplierListreducer } from "./Sessionreducer";
import { Disconnectreducer } from "./Disconnectreducer";
import { SupplierReducer } from "./SupplierReducer";
import {
  Cardoneloader,
  Cardtwoloader,
  Cardthreeloader,
  Cardfourloader,
  Cardfiveloader,
  Cardsixloader,
  Circuitamtloader,
  Circuitloader,
  Invoicechartloader,
  DisputeTypeloader,
  DisputeAmountloader,
  InstallOrdersByBW,
  InstallOrdersByTerm,
  InstallOrdersIn30Days,
  DisconnectOrdersLoader,
  ChangeOrdersOrderLoader,
  DisputableCircuitsTableLoader,
  TopCircuitsLoader,
  InvoiceDrillDownLoader,
  DisputeRaisedDownLoader,
  NewInstallDrillDownLoader,
  ChangeOrderDrillDownLoader,
  DisconnectOrderDrillDownLoader,
  DisconnectGraph,
  DisputeRaisedGraph,
  ChangeOrderGraph,
  NewInstallOrderGraph,
  DisputableCircuitsDrillDownLoader,
  OverallTrendDrillDownLoader,
  ChangeOrdersDrillDownLoader,
  DisconnectDrillDownLoader,
  InvoiceAmountDrillDownLoader,
  OpenLoseTableLoader,
  OpenLoseDrillDownLoader,
  ChatBotToggler,
  DirectLineController,
} from "./Loaderreducer";
import {
  Disputewinreducer,
  Winamtreducer,
  Lostamtreducer,
  Disputelostreducer,
  Unresolvedreducer,
  Unresolvedamtreducer,
  Winpercentage,
  Losspercentage,
  Unresolvedpercentage,
  Circuitsreducer,
} from "./Disputereducer";
import {DistrictSelectReducer} from './DistrictSelectReducer'
import {SentimentTopicReducer} from './SentimentTopicReducer'
import {TweetKeywordReducer} from './TweetKeywordReducer'
import {SelectTripReducer} from './SelectTripReducer';

const createRootReducer = (history) =>
  combineReducers({
    router: connectRouter(history),
    settings: Settings,
    auth: Auth,
    notes: Notes,
    contact: Contact,
    common: Common,
    //react: ReactTable,
    cone: Cardonereducer,
    ctwo: Cardtworeducer,
    cthree: Cardthreereducer,
    cfour: Cardfourreducer,
    cfive: Cardfivereducer,
    csix: Cardsixreducer,
    Disconnect: Disconnectreducer,
    Win: Disputewinreducer,
    Winamt: Winamtreducer,
    Lost: Disputelostreducer,
    Lostamt: Lostamtreducer,
    Unresolved: Unresolvedreducer,
    Unresolvedamt: Unresolvedamtreducer,
    Winpercent: Winpercentage,
    Losspercent: Losspercentage,
    Unresolvedpercent: Unresolvedpercentage,
    Raisedreducer: Raisedreducer,
    Newinstallreducer: Newinstallreducer,
    Changeordersreducer: Changeordersreducer,
    Disconnectordersreducer: Disconnectordersreducer,
    Circuitsreducer: Circuitsreducer,
    Winchartreducer: Winchartreducer,
    Losschartreducer: Losschartreducer,
    Unresolvedchartreducer: Unresolvedchartreducer,
    Raisedchartreducer: Raisedchartreducer,
    Newinstallchartreducer: Newinstallchartreducer,
    Changechartreducer: Changechartreducer,
    Disconnectchartreducer: Disconnectchartreducer,
    Disputechartreducer: Disputechartreducer,
    Invoicechartreducer: Invoicechartreducer,
    Indisp: Indispchartreducer,
    Orderbybw: InstallOrdersByBWreducer,
    Orderbyterm: InstallOrdersByTermreducer,
    Overall: InstallOrdersByOverallreducer,
    Changebydate: ChangeOrdersByDatereducer,
    Disconnectorder: DisconnectOrdersreducer,
    Topcircuits: TopCircuitsWithChangesreducer,
    Bycategory: DisputesByCategoryreducer,
    Invdrill: InvoiceDrilldownreducer,
    Disputedrill: DisputesDrillDownreducer,
    Installdrill: InstallOrdersDrillDownreducer,
    Changedrill: ChangeOrdersdrilldownreducer,
    Disconnectdrill: DisconnectOrdersDrillDownreducer,
    DisputableTable: DisputableCircuitsTablereducer,
    Amendent: Amendenturlreducer,
    DisConnectOrders: DisconnectOrdersDrillDownByDateReducer,
    InstallOrdersByDate: InstallOrdersDrillDownByDateReducer,
    ChangeOrders: ChangeOrdersDrillDownByDateReducer,
    InvoiceNumber: InvoiceNumberreducer,
    sessionSupplier: SupplierListreducer,
    InvoicesDrillDownForMonth: InvoicesDrillDownForMonth,
    InvoiceAmountDrillDownLoader: InvoiceAmountDrillDownLoader,
    OpenLoseTableLoader: OpenLoseTableLoader,
    OpenLoseDrillDownLoader: OpenLoseDrillDownLoader,
    ChatBotToggler: ChatBotToggler,
    DirectLineController: DirectLineController,
    // req: RequestReducer,
    Supplier: SupplierReducer,
    Invoicechart: Invoicechartloader,
    Circuitamt: Circuitamtloader,
    Circuit: Circuitloader,
    Cardone: Cardoneloader,
    Cardtwo: Cardtwoloader,
    Cardthree: Cardthreeloader,
    Cardfour: Cardfourloader,
    Cardfive: Cardfiveloader,
    Cardsix: Cardsixloader,
    DisputeAmount: DisputeAmountloader,
    DisputeType: DisputeTypeloader,
    InstallOrdersByBW: InstallOrdersByBW,
    InstallOrdersByTerm: InstallOrdersByTerm,
    InstallOrdersIn30Days: InstallOrdersIn30Days,
    DisconnectOrdersLoader: DisconnectOrdersLoader,
    ChangeOrdersOrderLoader: ChangeOrdersOrderLoader,
    TopCircuitsLoader: TopCircuitsLoader,
    DisputableCircuitsTableLoader: DisputableCircuitsTableLoader,
    InvoiceDrillDownLoader: InvoiceDrillDownLoader,
    DisputeRaisedDownLoader: DisputeRaisedDownLoader,
    NewInstallDrillDownLoader: NewInstallDrillDownLoader,
    ChangeOrderDrillDownLoader: ChangeOrderDrillDownLoader,
    DisconnectOrderDrillDownLoader: DisconnectOrderDrillDownLoader,
    DisconnectGraph: DisconnectGraph,
    DisputeRaisedGraph: DisputeRaisedGraph,
    ChangeOrderGraph: ChangeOrderGraph,
    NewInstallOrderGraph: NewInstallOrderGraph,
    DisputableCircuitsDrillDownLoader: DisputableCircuitsDrillDownLoader,
    OverallTrendDrillDownLoader: OverallTrendDrillDownLoader,
    ChangeOrdersDrillDownLoader: ChangeOrdersDrillDownLoader,
    DisconnectDrillDownLoader: DisconnectDrillDownLoader,
    OpenLoseDispute: OpenLoseDisputesTablereducer,

    District: DistrictSelectReducer,
    Sentiment: SentimentTopicReducer,
    TweetKeyword: TweetKeywordReducer,
    TripType: SelectTripReducer
  });

export default createRootReducer;
